[theme]
primaryColor = "#0b5f52"
backgroundColor = "#edf2f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#14242c"
font = "sans serif"
base = "light"

[server]
headless = true
maxUploadSize = 10
